tablebookingService:
  image: denisolek/table-booking:0.2.1
  ports:
    - "8080:8080"
  environment:
    DATABASE_HOST: tablebookingDb
    DATABASE_PORT: 5432
    DATABASE_NAME: tablebooking
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: 1
    DATABASE_DDL: create-drop
  links:
    - tablebookingDb

tablebookingDb:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: 1
    POSTGRES_USER: postgres
    POSTGRES_DB: tablebooking
